/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9b445484c830b2387b16b45ebf9210ef)
interface __BaseEnv_Env {
	JUSTONEAPI_MCP_CATALOG: KVNamespace;
	JUSTONEAPI_BASE_URL: "https://api.justoneapi.com";
	JUSTONEAPI_OPENAPI_URL: "https://docs.justoneapi.com/openapi.json";
	JUSTONEAPI_OPENAPI_ZH_URL: "https://docs.justoneapi.com/openapi-zh.json";
	JUSTONEAPI_SEARCH_V2_ENABLED: "true";
	JUSTONEAPI_CATALOG_REFRESH_INTERVAL_MS: "3600000";
	JUSTONEAPI_CATALOG_MEMORY_TTL_MS: "60000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "JUSTONEAPI_BASE_URL" | "JUSTONEAPI_OPENAPI_URL" | "JUSTONEAPI_OPENAPI_ZH_URL" | "JUSTONEAPI_SEARCH_V2_ENABLED" | "JUSTONEAPI_CATALOG_REFRESH_INTERVAL_MS" | "JUSTONEAPI_CATALOG_MEMORY_TTL_MS">> {}
}
