interface Env {
  JUSTONEAPI_ADMIN_TOKEN?: string;
  JUSTONEAPI_DEBUG?: string;
  JUSTONEAPI_SEARCH_V2_ENABLED?: string;
  JUSTONEAPI_TIMEOUT_MS?: string;
  JUSTONEAPI_RETRY?: string;
  JUSTONEAPI_OAUTH_MODE?: string;
  JUSTONEAPI_OAUTH_WORKER_ACTIVE_KID?: string;
  JUSTONEAPI_OAUTH_WORKER_PRIVATE_JWKS?: string;
  JUSTONEAPI_OAUTH_INTROSPECTION_CACHE_TTL_MS?: string;
  JUSTONEAPI_OAUTH_INTROSPECTION_CACHE_MAX_ENTRIES?: string;
  JUSTONEAPI_OAUTH_AS_TIMEOUT_MS?: string;
  JUSTONEAPI_MCP_ALLOWED_ORIGINS?: string;
}

declare namespace Cloudflare {
  interface Env {
    JUSTONEAPI_ADMIN_TOKEN?: string;
    JUSTONEAPI_DEBUG?: string;
    JUSTONEAPI_SEARCH_V2_ENABLED?: string;
    JUSTONEAPI_TIMEOUT_MS?: string;
    JUSTONEAPI_RETRY?: string;
    JUSTONEAPI_OAUTH_MODE?: string;
    JUSTONEAPI_OAUTH_WORKER_ACTIVE_KID?: string;
    JUSTONEAPI_OAUTH_WORKER_PRIVATE_JWKS?: string;
    JUSTONEAPI_OAUTH_INTROSPECTION_CACHE_TTL_MS?: string;
    JUSTONEAPI_OAUTH_INTROSPECTION_CACHE_MAX_ENTRIES?: string;
    JUSTONEAPI_OAUTH_AS_TIMEOUT_MS?: string;
    JUSTONEAPI_MCP_ALLOWED_ORIGINS?: string;
  }
}
