interface Env {
  JUSTONEAPI_ADMIN_TOKEN?: string;
  JUSTONEAPI_DEBUG?: string;
  JUSTONEAPI_SEARCH_V2_ENABLED?: string;
  JUSTONEAPI_PRIVATE_CATALOG_TERMS?: string;
  JUSTONEAPI_REQUIRE_PRIVATE_CATALOG_TERMS?: string;
  JUSTONEAPI_TIMEOUT_MS?: string;
  JUSTONEAPI_RETRY?: string;
}

declare namespace Cloudflare {
  interface Env {
    JUSTONEAPI_ADMIN_TOKEN?: string;
    JUSTONEAPI_DEBUG?: string;
    JUSTONEAPI_SEARCH_V2_ENABLED?: string;
    JUSTONEAPI_PRIVATE_CATALOG_TERMS?: string;
    JUSTONEAPI_REQUIRE_PRIVATE_CATALOG_TERMS?: string;
    JUSTONEAPI_TIMEOUT_MS?: string;
    JUSTONEAPI_RETRY?: string;
  }
}
